# 1.算术运算和数据对齐

In [2]:
import numpy as np
import pandas as pd

In [3]:
#Series
s1 = pd.Series(np.arange(4),index = ['a','b','c','d'])
s2 = pd.Series(np.arange(5),index = ['a','c','e','f','g'])

In [4]:
s1

a    0
b    1
c    2
d    3
dtype: int32

In [5]:
s2

a    0
c    1
e    2
f    3
g    4
dtype: int32

In [6]:
s1+s2

a    0.0
b    NaN
c    3.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [7]:
#DataFrame
df1 = pd.DataFrame(np.arange(12).reshape(4,3),index = ['a','b','c','d'],columns= list('ABC'))
df2 = pd.DataFrame(np.arange(9).reshape(3,3),index = ['a','d','f'],columns= list('ABD'))


In [8]:
df1

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [9]:
df2

A  B  D
a  0  1  2
d  3  4  5
f  6  7  8

In [14]:
df1+df2

A     B   C   D
a   0.0   2.0 NaN NaN
b   NaN   NaN NaN NaN
c   NaN   NaN NaN NaN
d  12.0  14.0 NaN NaN
f   NaN   NaN NaN NaN

# 2.使用填充值的算术方法

In [15]:
s1

a    0
b    1
c    2
d    3
dtype: int32

In [16]:
s2

a    0
c    1
e    2
f    3
g    4
dtype: int32

In [17]:
s1+s2

a    0.0
b    NaN
c    3.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [18]:
s1.add(s2,fill_value =0 )

a    0.0
b    1.0
c    3.0
d    3.0
e    2.0
f    3.0
g    4.0
dtype: float64

In [19]:
df1.add(df2,fill_value = 0)  #两个表中都没有的就是nan
df2.add(df1,fill_value = 0) 

A     B     C    D
a   0.0   2.0   2.0  2.0
b   3.0   4.0   5.0  NaN
c   6.0   7.0   8.0  NaN
d  12.0  14.0  11.0  5.0
f   6.0   7.0   NaN  8.0

In [32]:
1/df1

A         B         C
a       inf  1.000000  0.500000
b  0.333333  0.250000  0.200000
c  0.166667  0.142857  0.125000
d  0.111111  0.100000  0.090909

In [33]:
df1.rdiv(1)   #字母r开头  会翻转参数

A         B         C
a       inf  1.000000  0.500000
b  0.333333  0.250000  0.200000
c  0.166667  0.142857  0.125000
d  0.111111  0.100000  0.090909

In [37]:
df1.reindex(columns=df2.columns,fill_value=9)

A   B  D
a  0   1  9
b  3   4  9
c  6   7  9
d  9  10  9

# 3.DataFrame和Series混合运算

In [65]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [66]:
arr[0]

array([0, 1, 2, 3])

In [67]:
arr-arr[0]  #每一行都会减 这叫广播

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [68]:
df1

A   B   C
a  0   1   2
b  3   4   5
c  6   7   8
d  9  10  11

In [69]:
s3 =df1.iloc[0]
s3

A    0
B    1
C    2
Name: a, dtype: int32

In [70]:
df1-s3

A  B  C
a  0  0  0
b  3  3  3
c  6  6  6
d  9  9  9

In [72]:
s4 = df1['A']
s4

a    0
b    3
c    6
d    9
Name: A, dtype: int32

In [75]:
df1.sub(s4,axis=0)   # == axis=0

A  B  C
a  0  1  2
b  0  1  2
c  0  1  2
d  0  1  2