In [5]:
import numpy as np

In [6]:
a = np.arange(10)
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [7]:
b = np.array([1,2,3,4,5,],dtype='i1')
print(b)
print(b.dtype)

[1 2 3 4 5]
int8


In [8]:
c = np.array([1,2,3,4,5],dtype=np.float16)
print(c)
print(c.dtype)

[1. 2. 3. 4. 5.]
float16


In [12]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age
d = np.array([Person('知了',18),Person('课堂',20)])
print(d)
print(d.dtype)

object


In [13]:
f = np.array(['a','b'],dtype='S')
print(f)
print(f.dtype )

[b'a' b'b']
|S1


In [15]:
e = np.array(['a','c'],dtype='U')
print(e)
print(e.dtype)

['a' 'c']
<U1


In [16]:
uf = f.astype("U")
print(uf)
print(uf.dtype)
print(f.dtype)

['a' 'b']
<U1
|S1


# 总结：
1. 为什么Numpy的数组中有这么多的数据类型呢？
    * Numpy本身是基于C语言编写，C语言中本身就是有很多数据类型，所以直接引用过来了。
    * Numpy为了考虑到处理海量数据的性能，针对不同的数据给不同的数据类型，来节省内存空间，所以有不同的数据类型。

2. Numpy的数组的元素有哪些数据类型？

3. 使用ndarray.artype可以修改数组元素的数据类型。