In [4]:
import numpy as np

In [5]:
# 1. 一维数组的索引和切片
a1 = np.arange(10)
# 1.1 进行索引操作
print(a1[4])
# 1.2 进行切片操作
print(a1[4:6])
# 1.3 使用步长
print(a1[::2])
# 1.4 使用负数来作为索引
print(a1[-1])

4
[4 5]
[0 2 4 6 8]
9


In [6]:
# 2. 多维数组
# 也是通过中括号来索引和切片，在中括号中，使用逗号进行分割，逗号前面的是行，逗号后面的
# 是列，如果多维数组中只有一个值，那么这个值就是行
a2 = np.random.randint(0,10,size=(4,6))
print(a2)

[[8 6 2 2 6 7]
 [0 4 8 9 2 8]
 [9 9 9 8 6 4]
 [4 7 6 0 9 5]]


In [7]:
a2[0]
a2[1:3]
a2[[0,2,3]]

array([[8, 6, 2, 2, 6, 7],
       [9, 9, 9, 8, 6, 4],
       [4, 7, 6, 0, 9, 5]])

In [12]:
# a2[2,1]
#print(a2[[0,2],[4,5]])
#print(a2[1:3,4:6])
# a2[1:3,4:6]
a2[:,[1]]  #获取某列的值

array([[6],
       [4],
       [9],
       [7]])

# 索引和切片总结：
1. 如果数组是一维的，那么索引和切片就是跟python的列表是一样的。
2. 如果是多维的（这里以二维为例），那么在中括号中，给两个值，两个值是通过逗号分隔的，逗号前面的是行，逗号后面的是列。如果中括号中只有一个值，那么就是代表的是行。
3. 如果是多维数组（这里以二维为例），那么行的部分和列的部分，都是遵循一维数组的方式，可以使用整形，切片，还可以使用中括号的形式，来代表不连续的。比如a[[1,2],[3,4]]，那么返回的就是(1,3),(2,4)的两个值。
4. a[[1,1][2,3]] 和a[1][2,3]等价，但是a[[1,1][2,3，2]]不可以，因为不知道具体和什么配对

In [25]:
a2 = np.arange(24).reshape((4,6))
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [27]:
a2 < 10

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [28]:
a2[a2 < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a2[(a2 < 5) | (a2 > 10)]

array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])

# 布尔索引：
布尔索引是通过相同数组上的True还是False来进行提取的。提取的条件可以有多个，那么如果有多个，可以使用&来代表且，用|来代表或，如果有多个条件，那么每个条件要使用圆括号括起来。

In [79]:
a3 = np.random.randint(0,10,size=(3,5))
a3

array([[4, 6, 3, 2, 4],
       [3, 4, 9, 6, 5],
       [6, 3, 6, 5, 4]])

In [82]:
a3[1] = np.array([1,2,3,4,5])
a3

array([[4, 6, 3, 2, 4],
       [1, 2, 3, 4, 5],
       [6, 3, 6, 5, 4]])

In [84]:
a3[a3 < 3] = 1
a3

array([[4, 6, 3, 1, 4],
       [1, 1, 3, 4, 5],
       [6, 3, 6, 5, 4]])

In [88]:
result = np.where(a3<5,0,1)
result

array([[0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 0, 1, 1, 0]])

# 值的替换总结：
1. 可以使用索引或者切片来替换。
2. 使用条件索引来替换。
3. 使用where函数来实现。

# Numpy 索引和切片作业
1. 将`np.arange(10)`数组中的奇数全部替换成`-1`

In [14]:
import numpy as np
a1 = np.arange(10)
print(a1)
a1[a1%2!=0] = -1
print(a1)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


2. 有一个4行4列的数组（比如：`np.random.randint(0,10,size=(4,4))`），请讲其中对角线中的数取出形成一个一维数组。（用`np.eye`）

In [16]:
a2 = np.random.randint(0,10,size = (4,4))
print(a2)
a3 = np.eye(4,4)
a4 = a2[a3 == 1]
print(a4)

[[5 6 8 0]
 [4 8 5 2]
 [7 1 5 0]
 [7 3 1 5]]
[5 8 5 5]


3. 有一个四行三列的数组，请取出其中（0,0）（1，2）（3,2）的点

In [17]:
a5 = np.random.random((4,3))
print(a5)
print(a5[[0,1,3],[0,2,2]])

[[0.78355922 0.17518578 0.53868618]
 [0.76659882 0.91144694 0.18089434]
 [0.26173167 0.33243837 0.37536986]
 [0.41856675 0.00664939 0.47196103]]
[0.78355922 0.18089434 0.47196103]


4. 有一个四行四列的数组请取出其中2-3行包括第三行的所有数据

In [20]:
a6 = np.random.random((4,4))
print(a6)
print(a6[2:4])

[[0.96760907 0.86035729 0.62809194 0.05423024]
 [0.27181694 0.67828039 0.03662483 0.06857537]
 [0.37484166 0.52634349 0.55672763 0.14980909]
 [0.15752824 0.18844953 0.22066504 0.7307545 ]]
[[0.37484166 0.52634349 0.55672763 0.14980909]
 [0.15752824 0.18844953 0.22066504 0.7307545 ]]


5. 有一个八行九列的数组，请将其中1-5行包括第五行的第八行，大于三的数字全部取出来

In [23]:
a7 = np.random.randint(1,10,(8,9))
print(a7)
a7 = a7[1:6,8]
print(a7[a7>3])

[[6 9 5 9 4 1 6 1 4]
 [7 8 3 4 5 7 2 2 8]
 [3 8 8 7 8 6 1 3 7]
 [7 2 3 1 9 4 4 5 1]
 [7 3 3 3 1 5 3 9 3]
 [6 3 9 3 4 6 4 1 8]
 [7 6 4 9 9 8 1 3 6]
 [3 9 5 7 8 9 6 9 6]]
[8 7 8]
