In [2]:
import numpy as np

#### 1. 第一题：将np.arange(10)数组中的奇数全部都替换成-1

In [4]:
a1 = np.arange(10)
a1[a1%2 != 0] = -1
print(a1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


#### 2. 第二题：有一个4行4列的数组（比如：np.random.randint(0,10,size=(4,4))），请将其中对角线的数取出来形成一个一维数组。提示（使用np.eye）。

In [7]:
a2 = np.random.randint(0,10,size=(4,4))
eye = np.eye(4,dtype=bool)
a3 = a2[eye]
print(a2)
print(a3)

[[9 3 1 2]
 [7 4 8 6]
 [5 6 7 6]
 [4 7 9 5]]
[9 4 7 5]


#### 3. 有一个4行4列的数组，请取出其中(0,0),(1,2),(3,2)的点。

In [10]:
a4 = np.random.randint(0,10,size=(4,4))
points = a4[[0,1,3],[0,2,2]]
print(a4)
print(points)

[[1 1 4 9]
 [2 4 2 8]
 [4 9 5 8]
 [0 0 6 7]]
[1 2 6]


#### 4.有一个4行4列的数组，请取出其中2-3行（包括第3行）的所有数据。

In [11]:
a5 = np.random.randint(0,10,size=(4,4))
lines = a5[2:4]
print(a5)
print(lines)

[[7 1 5 4]
 [2 5 3 9]
 [2 5 1 3]
 [6 6 2 7]]
[[2 5 1 3]
 [6 6 2 7]]


##### 5. 有一个8行9列的数组，请将其中1-5行（包含第5行）的第8列大于3的数全部都取出来。

In [16]:
a6 = np.random.randint(0,10,size=(8,9))
a6

array([[0, 6, 2, 0, 7, 1, 3, 3, 3],
       [7, 9, 6, 5, 8, 8, 5, 3, 6],
       [9, 8, 7, 8, 3, 8, 5, 8, 1],
       [7, 1, 8, 3, 1, 1, 0, 9, 5],
       [7, 4, 4, 8, 0, 7, 2, 1, 7],
       [6, 3, 5, 5, 2, 3, 3, 2, 7],
       [5, 8, 9, 4, 3, 6, 2, 6, 4],
       [4, 7, 5, 8, 5, 7, 9, 9, 2]])

In [19]:
# 先获取指定部分的数据条件的数组
conditions = a6[1:6,8] > 3
print(conditions)
# 再获取指定部分的数据
datas = a6[1:6,8]
print(datas)
# 再从数组中提取符合条件的数据
result = datas[conditions]
print(result)

[ True False  True  True  True]
[6 1 5 7 7]
[6 5 7 7]
