In [2]:
import numpy as np

In [3]:
a1 = np.random.randint(0,10,size=(3,4))
a1

array([[1, 6, 8, 7],
       [8, 9, 9, 5],
       [7, 4, 6, 5]])

In [4]:
a1.reshape((2,6))

array([[1, 6, 8, 7, 8, 9],
       [9, 5, 7, 4, 6, 5]])

In [5]:
a1

array([[1, 6, 8, 7],
       [8, 9, 9, 5],
       [7, 4, 6, 5]])

In [6]:
a1.resize((4,3))

In [7]:
a1

array([[1, 6, 8],
       [7, 8, 9],
       [9, 5, 7],
       [4, 6, 5]])

In [3]:
# flatten和ravel函数：
a2 = np.random.randint(0,10,size=(3,4))
print(a2)

[[3 8 9 3]
 [4 6 7 5]
 [1 2 0 9]]


In [4]:
a3 = a2.flatten()
a3[0] = 100
print(a2[0,0])
a3

3


array([100,   8,   9,   3,   4,   6,   7,   5,   1,   2,   0,   9])

In [19]:
a4 = a2.ravel()
a4[0] = 100
print(a2[0,0])

100


In [22]:
a2

array([[3, 6, 5, 9],
       [4, 0, 8, 9],
       [4, 6, 2, 1]])

In [43]:
vstack1 = np.random.randint(0,10,size=(3,4))
vstack1

array([[6, 2, 5, 2],
       [4, 2, 5, 7],
       [0, 1, 9, 9]])

In [56]:
vstack2 = np.random.randint(0,10,size=(2,4))
vstack2

array([[3, 1, 7, 8],
       [7, 0, 9, 2]])

In [58]:
# vstack3 = np.vstack([vstack1,vstack2])
vstack3 = np.concatenate([vstack1,vstack2],axis=0)
vstack3

array([[6, 2, 5, 2],
       [4, 2, 5, 7],
       [0, 1, 9, 9],
       [3, 1, 7, 8],
       [7, 0, 9, 2]])

In [49]:
h1 = np.random.randint(0,10,size=(3,4))
h1

array([[0, 6, 0, 6],
       [4, 0, 3, 5],
       [2, 3, 4, 2]])

In [54]:
h2 = np.random.randint(0,10,size=(3,1))
h2

array([[5],
       [8],
       [3]])

In [59]:
# h3 = np.hstack([h2,h1])
h3 = np.concatenate([h2,h1],axis=1)
h3

array([[5, 0, 6, 0, 6],
       [8, 4, 0, 3, 5],
       [3, 2, 3, 4, 2]])

In [69]:
hs1 = np.random.randint(0,10,size=(3,4))
print(hs1)

[[5 8 6 7]
 [9 6 8 8]
 [2 2 2 8]]


In [70]:
np.hsplit(hs1,2)

[array([[5, 8],
        [9, 6],
        [2, 2]]), array([[6, 7],
        [8, 8],
        [2, 8]])]

In [72]:
np.hsplit(hs1,(1,2))

[array([[5],
        [9],
        [2]]), array([[8],
        [6],
        [2]]), array([[6, 7],
        [8, 8],
        [2, 8]])]

In [73]:
vs1 = np.random.randint(0,10,size=(4,5))
print(vs1)

[[8 2 5 6 6]
 [7 9 3 8 0]
 [5 9 1 1 2]
 [2 0 4 3 9]]


In [74]:
np.vsplit(vs1,4)

[array([[8, 2, 5, 6, 6]]),
 array([[7, 9, 3, 8, 0]]),
 array([[5, 9, 1, 1, 2]]),
 array([[2, 0, 4, 3, 9]])]

In [75]:
np.vsplit(vs1,(1,3))

[array([[8, 2, 5, 6, 6]]), array([[7, 9, 3, 8, 0],
        [5, 9, 1, 1, 2]]), array([[2, 0, 4, 3, 9]])]

In [76]:
np.split(hs1,4,axis=1)

[array([[5],
        [9],
        [2]]), array([[8],
        [6],
        [2]]), array([[6],
        [8],
        [2]]), array([[7],
        [8],
        [8]])]

In [80]:
np.split(vs1,4,axis=0)

[array([[8, 2, 5, 6, 6]]),
 array([[7, 9, 3, 8, 0]]),
 array([[5, 9, 1, 1, 2]]),
 array([[2, 0, 4, 3, 9]])]

In [134]:
t1 = np.random.randint(0,10,size=(2,4))
print(t1)

[[9 7 3 3]
 [9 3 4 0]]


In [135]:
t1.T

array([[9, 9],
       [7, 3],
       [3, 4],
       [3, 0]])

In [136]:
t1.dot(t1.T)

array([[148, 114],
       [114, 106]])

In [141]:
t2 = t1.transpose()
t2[0] = 100
t1

array([[100,   7,   3,   3],
       [100,   3,   4,   0]])

# 总结：

### 数组的形状改变：
1. reshape和resize都是重新定义形状的。但是reshape不会修改数组本身，而是将修改后的结果返回回去，而resize是直接修改数组本书的。
2. flatten和ravel都是用来将数组边成一维数组的，并且他们都不会对原数组造成修改，但是flatten返回的是一个拷贝，所以对flatten的返回值的修改不会影响到原来数组，而ravel返回的是一个View，那么对返回值的修改会影响到原来数组的值。

### 数组的叠加：
1. hstack代表在水平方向叠加，如果想要叠加成功，那么他们的行必须一致。
2. vstack代表在垂直方向叠加，如果想要叠加成功，那么他们的列必须一致。
3. concatenate可以手动的指定axis参数具体在哪个方向叠加，如果axis=0，代表在水平方向叠加，如果axis=1，代表在垂直方向叠加，如果axis=None，那么会先进行叠加，再转换成1维数组。

### 数组的切割：
1. hsplit代表在水平方向切割，按列进行切割的。他的切割方式有两种，第一种就是直接指定平均切割成多少列，第二种就是指定切割的下标值。
2. vsplit代表在垂直方向切割，按行进行切割。他的切割方式跟hsplit是一样的。
3. split/array_split是手动的指定axis参数，axis=0,代表按行进行切割，axis=1，代表按列进行切割。

### 矩阵转置：
1. 可以通过ndarray.T的形式进行转置。
2. 也可以通过ndarray.transpose()进行转置，这个方法返回的是一个View，所以对返回值上进行修改，会影响到原来的数组。