In [13]:
import numpy as np

In [14]:
data = np.random.randint(0,10,size=(3,5))
data

array([[4, 4, 7, 7, 8],
       [6, 5, 9, 8, 1],
       [7, 8, 4, 3, 0]])

In [15]:
data = data.astype(np.float)  #NAN是浮点型
data[0,1] = np.NAN
data

C:\Users\warr\AppData\Local\Temp\ipykernel_13264\683604557.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data = data.astype(np.float)  #NAN是浮点型


array([[ 4., nan,  7.,  7.,  8.],
       [ 6.,  5.,  9.,  8.,  1.],
       [ 7.,  8.,  4.,  3.,  0.]])

In [16]:
data[0,1]*2

nan

In [17]:
data[1,2] = np.NAN
data

array([[ 4., nan,  7.,  7.,  8.],
       [ 6.,  5., nan,  8.,  1.],
       [ 7.,  8.,  4.,  3.,  0.]])

In [18]:
data[~np.isnan(data)]

array([4., 7., 7., 8., 6., 5., 8., 1., 7., 8., 4., 3., 0.])

In [19]:
lines = np.where(np.isnan(data))[0]
np.delete(data,lines,axis=0)

array([[7., 8., 4., 3., 0.]])

In [20]:
scores = np.loadtxt("nan_scores.csv",delimiter=",",skiprows=1,encoding="utf-8",dtype=np.str)
scores[scores == ""] = np.NAN
scores1 = scores.astype(np.float)
scores1[np.isnan(scores1)] = 0
# 除了delete用axis=0表示行以外，其他的大部分函数都是axis=1来表示行。
print(scores1.sum(axis=0))

[284.  278.5]


C:\Users\warr\AppData\Local\Temp\ipykernel_13264\1180263528.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  scores = np.loadtxt("nan_scores.csv",delimiter=",",skiprows=1,encoding="utf-8",dtype=np.str)
C:\Users\warr\AppData\Local\Temp\ipykernel_13264\1180263528.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  scores1 = scores.astype(np.float

In [21]:
scores2 = scores.astype(np.float)
for x in range(scores2.shape[1]):
    col = scores2[:,x]
    non_nan_col = col[~np.isnan(col)]
    mean = non_nan_col.mean()
    col[np.isnan(col)] = mean
scores2

C:\Users\warr\AppData\Local\Temp\ipykernel_13264\1073533779.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  scores2 = scores.astype(np.float)


array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [34. , 55.7],
       [56.8, 56. ],
       [23. , 56. ]])

# 总结：
1. NAN：Not A Number的简写，不是一个数字，但是他是属于浮点类型。
2. INF：无穷大，在除数为0的情况下会出现INF。
3. NAN和所有的值进行计算结果都是等于NAN
4. NAN != NAN
5. 可以通过np.isnan来判断某个值是不是NAN。
6. 处理值的时候，可以通过删除NAN的形式进行处理，也可以通过值的替换进行处理。
7. np.delete比较特殊，他通过axis=0来代表行，而其他大部分函数是通过axis=1来代表行。