In [2]:
import numpy as np

In [4]:
a = np.arange(0,4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [5]:
a.sum(axis=0)

array([2, 4])

In [6]:
a.sum(axis=1)

array([1, 5])

In [8]:
x = np.arange(12).reshape(2,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [11]:
x.max(axis=1)

array([ 5, 11])

In [13]:
np.delete(x,0,axis=0)

array([[ 6,  7,  8,  9, 10, 11]])

In [14]:
y = np.arange(24).reshape(2,2,6)
y

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [15]:
y.max(axis=0)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## 总结：
1. 最外面的括号代表着 axis=0，依次往里的括号对应的 axis 的计数就依次加 1
2. 操作方式：如果指定轴进行相关的操作，那么他会使用轴下的每个直接子元素的第0个，第1个，第2个...分别进行相关的操作。
3. np.delete，是直接删除指定轴下的第几个直接子元素。