In [1]:
import numpy as np

In [2]:
a = np.random.uniform(-10,10,size=(3,5))
a

array([[-6.71149229, -2.17809525,  8.57545287, -5.31680944, -5.84956773],
       [-8.57309185, -5.76927816, -9.8563885 ,  2.79138433, -1.8064904 ],
       [-6.96541888, -2.77797572, -6.22511018, -7.55583726,  0.24365377]])

In [3]:
# 1. np.abs
np.abs(a)

array([[6.71149229, 2.17809525, 8.57545287, 5.31680944, 5.84956773],
       [8.57309185, 5.76927816, 9.8563885 , 2.79138433, 1.8064904 ],
       [6.96541888, 2.77797572, 6.22511018, 7.55583726, 0.24365377]])

In [4]:
# 2. np.sqrt
np.sqrt(a)

D:\ProgramApp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


array([[       nan,        nan, 2.92838742,        nan,        nan],
       [       nan,        nan,        nan, 1.67074364,        nan],
       [       nan,        nan,        nan,        nan, 0.49361298]])

In [5]:
# 3. np.square
np.square(a)

array([[4.50441288e+01, 4.74409890e+00, 7.35383919e+01, 2.82684626e+01,
        3.42174426e+01],
       [7.34979038e+01, 3.32845704e+01, 9.71483943e+01, 7.79182645e+00,
        3.26340755e+00],
       [4.85170601e+01, 7.71714912e+00, 3.87519968e+01, 5.70906766e+01,
        5.93671608e-02]])

In [6]:
# 4. np.exp
np.exp(a)

array([[1.21684688e-03, 1.13257052e-01, 5.29995109e+03, 4.90838930e-03,
        2.88114432e-03],
       [1.89126993e-04, 3.12201031e-03, 5.24112914e-05, 1.63035736e+01,
        1.64229507e-01],
       [9.43967446e-04, 6.21642176e-02, 1.97910575e-03, 5.23048034e-04,
        1.27590250e+00]])

In [7]:
# 5. np.log
np.log(a)

D:\ProgramApp\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  


array([[        nan,         nan,  2.1489038 ,         nan,         nan],
       [        nan,         nan,         nan,  1.02653765,         nan],
       [        nan,         nan,         nan,         nan, -1.41200703]])

In [8]:
# 6. np.sign
np.sign(a)

array([[-1., -1.,  1., -1., -1.],
       [-1., -1., -1.,  1., -1.],
       [-1., -1., -1., -1.,  1.]])

In [9]:
# 7. np.ceil
np.ceil(a)

array([[-6., -2.,  9., -5., -5.],
       [-8., -5., -9.,  3., -1.],
       [-6., -2., -6., -7.,  1.]])

In [10]:
# 8. np.floor
np.floor(a)

array([[ -7.,  -3.,   8.,  -6.,  -6.],
       [ -9.,  -6., -10.,   2.,  -2.],
       [ -7.,  -3.,  -7.,  -8.,   0.]])

In [11]:
# 8. np.rint或者np.round
np.rint(a)

array([[ -7.,  -2.,   9.,  -5.,  -6.],
       [ -9.,  -6., -10.,   3.,  -2.],
       [ -7.,  -3.,  -6.,  -8.,   0.]])

In [13]:
# 9. np.modf
np.modf(a)[1]

array([[-6., -2.,  8., -5., -5.],
       [-8., -5., -9.,  2., -1.],
       [-6., -2., -6., -7.,  0.]])

In [14]:
# 10. np.sin
np.sin(a)

array([[-0.41533131, -0.82119239,  0.7508348 ,  0.82283158,  0.42015632],
       [-0.75239214,  0.49158346,  0.41833419,  0.3430935 , -0.9723525 ],
       [-0.63052822, -0.35565699,  0.05804249, -0.95588322,  0.24125008]])

In [21]:
a+1

array([[-5.71149229, -1.17809525,  9.57545287, -4.31680944, -4.84956773],
       [-7.57309185, -4.76927816, -8.8563885 ,  3.79138433, -0.8064904 ],
       [-5.96541888, -1.77797572, -5.22511018, -6.55583726,  1.24365377]])

In [24]:
np.add(a,np.random.randint(0,5,size=(3,1)))

array([[-4.71149229, -0.17809525, 10.57545287, -3.31680944, -3.84956773],
       [-6.57309185, -3.76927816, -7.8563885 ,  4.79138433,  0.1935096 ],
       [-5.96541888, -1.77797572, -5.22511018, -6.55583726,  1.24365377]])

In [27]:
# a[a > 0]
a[np.greater(a,0)]

array([8.57545287, 2.79138433, 0.24365377])

In [29]:
# a[(a > 0) & (a < 5)]
a[np.logical_and(a>0,a<5)]

array([2.79138433, 0.24365377])

In [33]:
# a[(a > 5) | (a < 0)]
a[np.logical_or(a>5,a<0)]

array([-6.71149229, -2.17809525,  8.57545287, -5.31680944, -5.84956773,
       -8.57309185, -5.76927816, -9.8563885 , -1.8064904 , -6.96541888,
       -2.77797572, -6.22511018, -7.55583726])

# 聚合函数

In [47]:
# 1. sum
np.sum(a,axis=0)

array([-22.25000302, -10.72534913,  -7.50604581, -10.08126237,
        -7.41240435])

In [48]:
np.prod(a,axis=0)

array([-400.77794201,  -34.90814664,  526.16495724,  112.13813404,
          2.5747352 ])

In [51]:
np.mean(a,axis=0)

array([-7.41666767, -3.57511638, -2.50201527, -3.36042079, -2.47080145])

In [53]:
np.std(a,axis=0)

array([0.82426021, 1.5707161 , 7.97200397, 4.44498527, 2.53151061])

In [57]:
print(a)
print(np.min(a,axis=0))
print(np.argmin(a,axis=0))

[[-6.71149229 -2.17809525  8.57545287 -5.31680944 -5.84956773]
 [-8.57309185 -5.76927816 -9.8563885   2.79138433 -1.8064904 ]
 [-6.96541888 -2.77797572 -6.22511018 -7.55583726  0.24365377]]
[-8.57309185 -5.76927816 -9.8563885  -7.55583726 -5.84956773]
[1 1 1 2 0]


In [58]:
np.median(a)

-5.76927815516961

In [59]:
%time sum(np.arange(1000000))

Wall time: 160 ms


D:\ProgramApp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in long_scalars
  """Entry point for launching an IPython kernel.


1783293664

In [60]:
%time np.sum(np.arange(1000000))

Wall time: 3.99 ms


1783293664

# 布尔判断函数：

In [73]:
b = np.arange(0,10)
b.any()

True

In [77]:
(a>=0).any()

True

In [81]:
np.sort(a,axis=0)

array([[-6.71149229, -2.17809525,  8.57545287, -5.31680944, -5.84956773],
       [-8.57309185, -5.76927816, -9.8563885 ,  2.79138433, -1.8064904 ],
       [-6.96541888, -2.77797572, -6.22511018, -7.55583726,  0.24365377]])

In [82]:
b = np.random.randint(0,10,size=(3,5))
b

array([[2, 8, 4, 3, 7],
       [3, 4, 4, 2, 9],
       [9, 9, 5, 5, 2]])

In [83]:
b.sort()

In [84]:
b

array([[2, 3, 4, 7, 8],
       [2, 3, 4, 4, 9],
       [2, 5, 5, 9, 9]])

In [88]:
np.argsort(a,axis=0)

array([[1, 1, 1, 2, 0],
       [2, 2, 2, 0, 1],
       [0, 0, 0, 1, 2]], dtype=int64)

In [90]:
-np.sort(-a)

array([[ 8.57545287, -2.17809525, -5.31680944, -5.84956773, -6.71149229],
       [ 2.79138433, -1.8064904 , -5.76927816, -8.57309185, -9.8563885 ],
       [ 0.24365377, -2.77797572, -6.22511018, -6.96541888, -7.55583726]])

In [91]:
indexes = np.argsort(-a)
np.take(a,indexes)

array([[ 8.57545287, -2.17809525, -5.31680944, -5.84956773, -6.71149229],
       [-5.31680944, -5.84956773, -2.17809525, -6.71149229,  8.57545287],
       [-5.84956773, -2.17809525,  8.57545287, -6.71149229, -5.31680944]])

# 其他函数补充：

In [92]:
# 1. apply_along_axis：
c = np.random.randint(0,100,size=(3,20))
c

array([[31,  1, 69,  3, 92, 95, 47, 61, 51, 15, 41, 63, 27, 88, 30, 49,
        90, 93, 21, 89],
       [82, 39, 25, 20, 15, 88, 83, 91, 83, 61, 10,  0, 33, 11, 36, 95,
        50, 54, 41, 27],
       [11, 71, 17, 66, 83, 30, 26, 10, 26, 58, 29, 28, 86, 57, 29, 49,
        57, 31, 74, 35]])

In [99]:
# def get_mean(x):
#     y = x[np.logical_and(x!=x.max(),x!=x.min())].mean()
#     return y
np.apply_along_axis(lambda x:x[np.logical_and(x!=x.max(),x!=x.min())].mean(),axis=0,arr=c)

D:\ProgramApp\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: Mean of empty slice.
  after removing the cwd from sys.path.
D:\ProgramApp\Anaconda3\lib\site-packages\numpy\core\_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


array([31., 39., 25., 20., 83., 88., 47., 61., 51., 58., 29., 28., 33.,
       57., 30., nan, 57., 54., 41., 35.])

In [102]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [103]:
d = np.random.randint(0,10,size=(3,5))
d

array([[8, 0, 1, 0, 7],
       [4, 9, 7, 3, 3],
       [4, 0, 9, 4, 0]])

In [108]:
np.unique(d,return_counts=True)

(array([0, 1, 3, 4, 7, 8, 9]), array([4, 1, 2, 3, 2, 1, 2], dtype=int64))

# Numpy练习题
1. 查看Numpy的版本号：

In [1]:
import numpy as np
print(np.__version__)

1.21.5


2. 如何创建一个所有值都是False的布尔类型的数组：

In [3]:
np.full((3,3),False)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

3. 将一个有10个数的数组形状进行转换

In [9]:
a = np.random.rand(3,3,3)
print(a)
print(a.reshape(9,3))

[[[0.64600659 0.22733259 0.95115502]
  [0.99516291 0.09889597 0.27177055]
  [0.47472396 0.3137703  0.17879279]]

 [[0.50696739 0.62503398 0.12395132]
  [0.29954564 0.058083   0.37407908]
  [0.62381323 0.29549067 0.44868734]]

 [[0.76341491 0.38453856 0.98397215]
  [0.75222677 0.86122266 0.21842175]
  [0.21061871 0.11900257 0.64141244]]]
[[0.64600659 0.22733259 0.95115502]
 [0.99516291 0.09889597 0.27177055]
 [0.47472396 0.3137703  0.17879279]
 [0.50696739 0.62503398 0.12395132]
 [0.29954564 0.058083   0.37407908]
 [0.62381323 0.29549067 0.44868734]
 [0.76341491 0.38453856 0.98397215]
 [0.75222677 0.86122266 0.21842175]
 [0.21061871 0.11900257 0.64141244]]


4. 将数组中所有偶数都替换成0（改变原来数组和不改变原来数组两种实现）：

In [13]:
a = np.arange(10)
b = np.where(a%2==0,0,a)
print(a)
print(b)
a[a%2==0] = 0
print(a)

[0 1 2 3 4 5 6 7 8 9]
[0 1 0 3 0 5 0 7 0 9]
[0 1 0 3 0 5 0 7 0 9]


5. 创建一个一维且有10个数的数组，元素是从  0-1 之间，
但是不包含0和1：

In [15]:
print(np.linspace(0,1,12)[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


6. 求以下数组大于等于5并且小于等于10的数组：

In [19]:
a = np.arange(15)
print(a[(a>=5)&(a<=10)])
print(a[np.where((a>=5)&(a<=10))])


[ 5  6  7  8  9 10]
[ 5  6  7  8  9 10]


7. 将一个二维数组的行和列分别逆向

In [22]:
a = np.random.randint(1,10,(4,4))
print(a)
b = a[::-1]
print(b)
c = a[:,::-1]
print(c)

[[4 3 5 7]
 [5 2 8 4]
 [4 8 8 4]
 [2 2 7 7]]
[[2 2 7 7]
 [4 8 8 4]
 [5 2 8 4]
 [4 3 5 7]]
[[7 5 3 4]
 [4 8 2 5]
 [4 8 8 4]
 [7 7 2 2]]


8. 如何将科学计数法转换为浮点类型打印

In [25]:
np.set_printoptions(suppress = True,precision=6)
a = np.random.random((3,3))/1e3
print((a))

[[0.000125 0.000865 0.000573]
 [0.000095 0.000341 0.000881]
 [0.000576 0.00036  0.000618]]


9. 获取一个数组中唯一的元素：

In [27]:
arr = np.random.randint(0,20,(10,10))
print(np.unique(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [28]:
arr = np.random.randint(0,20,(10,10))
np.unique(arr,return_counts=True)

(array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19]),
 array([8, 2, 5, 8, 5, 7, 3, 5, 6, 5, 9, 9, 6, 5, 5, 3, 2, 4, 3],
       dtype=int64))

11. 十一、如何找到数组中每行的最大值：

In [38]:
a = np.random.randint(1,10,(3,3))
print(a)
b = np.apply_along_axis(lambda x:print(np.max(x)),axis = 1,arr =a)
print(np.max(a,axis = 1))

[[1 8 1]
 [9 1 2]
 [4 3 9]]
8
9
9
[9 8 9]


12. 如何按照行球最小值和最大值相除的结果：

In [40]:
a = np.random.randint(1,10,(3,3))
np.apply_along_axis(lambda x:print(np.max(x)/np.min(x)),axis = 1,arr =a)

3.0
2.25
1.6


array([None, None, None], dtype=object)

13. 判断两个数组是否完全相等

In [42]:
a = np.random.random(10)
b = np.random.random(10)
print((a==b).all())

False


14. 设置一个数组不能修改值：

In [ ]:
a = np.zeros((2,2))
a.flags.writable = False
a[0] = 1

15. 找到数组中离某个元素的最近的值：